### PR TITLE
Pin Setup tools

### PR DESCRIPTION
**Pull request by aht007**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @aht007! I've created [OSPR-6347](https://openedx.atlassian.net/browse/OSPR-6347) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Review by mraarif — APPROVED** [review]

**Review by iamsobanjaved — APPROVED** [review]

**Comment by edx-webhook** [comment]
Although this pull request is already merged, I've created [OSPR-6349](https://openedx.atlassian.net/browse/OSPR-6349) so that we can track it in Jira.

There is nothing you have to do. No action is needed from your side.  Thanks again for your contribution.

**Comment by nedbat** [comment]
I'm trying to understand why this pin is here.  There's no reason given in the PR, the commit, or the file.  This makes it difficult to decide when to update the pin. @iamsobanjaved @aht007 @mraarif

**Comment by mraarif** [comment]
@iamsobanjaved @aht007 can you help @nedbat understand

**Comment by aht007** [comment]
@nedbat `setuptools` version 60.0 caused issues in several services' pipeline. The slack conversation around the issue has been deleted now but this [github issue](https://github.com/pypa/setuptools/issues/2940) from setuptools repo contains information about the problem that setuptools version 60 caused. I will go ahead and create a PR to add description with the pin.

**Pull request merged**
