### PR TITLE
feat: add lint checker for Open edX Events code-annotations

### PR DESCRIPTION
**Pull request by mariajgrimaldi**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mariajgrimaldi! I've created [OSPR-5942](https://openedx.atlassian.net/browse/OSPR-5942) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by natabene** [comment]
@mariajgrimaldi Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by sarina** [comment]
@mariajgrimaldi I see this has been on our Jira board for quite some time. Do you have a ballpark on when you'll be returning to this work?

**Comment by natabene** [comment]
@mariajgrimaldi Just checking if this PR is still in the works and relevant.

**Comment by mariajgrimaldi** [comment]
Hey there @natabene, let's close this for now.

**Comment by edx-webhook** [comment]
@mariajgrimaldi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-lint&entry.867055334=https://github.com/openedx/edx-lint/pull/176&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2021-07-29+13:26&entry.1917517419=2022-01-17+17:53&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
