### PR TITLE
fix: remove deleted pylint warnings from pylintrc

### PR DESCRIPTION
**Pull request by UsamaSadiq**
**Issue:** [BOM-3451](https://2u-internal.atlassian.net/browse/BOM-3451)

### Description
- `pylint>2.14.0` introduced a new warning `useless-option-value` for the warnings which haven been deleted from pylint. This change is now causing quality failures in a lot of repos when upgrading pylint package. Some example PRs are https://github.com/openedx/bok-choy/pull/383 and https://github.com/openedx/edx-django-utils/pull/220.
- Updated `pylintrc` to remove deleted pylint warnings mentioned in [pylint deleted warnings](https://github.com/PyCQA/pylint/blob/a5ca674cf12f3bffbd90370c7595ec2f20abe953/pylint/message/_deleted_message_ids.py).

### CODE REVIEW

**Review by aht007 — APPROVED** [review]
LGTM

**Review by nedbat — APPROVED** [review]

**Comment by pshiu** [comment]
@UsamaSadiq, thanks for this work! FYI, @ashultz0's newly-created repo [program-intent-engagement](https://github.com/edx/program-intent-engagement/tree/ashultz0/init-cookiecut2) is a brand new cookiecutter repo that's still getting a few pylint warnings, even after a `edx_lint update` as of this comment. Details below in case it's related:

<details>
<summary>Console output</summary>
    
    % edx_lint update
    % make quality | sort | uniq
    pylintrc:1:0: E0015: Unrecognized option found: files-output, bad-functions, no-space-check (unrecognized-option)
    pylintrc:1:0: R0022: Useless option value for '--enable', 'indexing-exception' was removed from pylint, see https://github.com/PyCQA/pylint/pull/4942. (useless-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--disable', expected a valid pylint message and got 'locally-enabled' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--disable', expected a valid pylint message and got 'long-suffix' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--disable', expected a valid pylint message and got 'lowercase-l-suffix' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--disable', expected a valid pylint message and got 'misplaced-comparison-constant' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--disable', expected a valid pylint message and got 'no-self-use' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--disable', expected a valid pylint message and got 'non-ascii-bytes-literal' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--disable', expected a valid pylint message and got 'old-ne-operator' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--disable', expected a valid pylint message and got 'old-octal-literal' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'cyclical-import' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'eq-without-hash' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'invalid-encoded-data' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'missing-super-argument' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'mixed-fomat-string' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'nonimplemented-raised' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'nonstandard-exception' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'old-style-class' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'property-on-old-class' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'redefined-in-handler' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'redefined-variable-type' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'relative-import' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'slots-on-old-class' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'super-on-old-class' (unknown-option-value)
    pylintrc:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'unbalance-tuple-unpacking' (unknown-option-value)

</details>

**Comment by UsamaSadiq** [comment]
@pshiu thanks for highlighting the issue. There were still some configurations remaining which have now been updated in the latest PR and the cookie-cutters repo has also been tested with the latest hash. 
Hopefully, now there won't be any issue with any newly created repo.

**Comment by pshiu** [comment]
Fantastic. Just tested after re-running `make upgrade; edx_lint update` on [program-intent-engagement](https://github.com/edx/program-intent-engagement/tree/ashultz0/init-cookiecut2) and it passes (minus 1 expected pylint message). Thank you, @UsamaSadiq.  cc: @ashultz0

**Comment by ashultz0** [comment]
confirmed this works on program-intent-engagement, thanks @UsamaSadiq

**Comment by ashultz0** [comment]
I had different behavior between local make quality and CI make quality and had to do a few shenanigans to get things working but it made it through in the end on https://github.com/edx/program-intent-engagement/pull/3

**Pull request merged**
